# Generated by Django 5.0.4 on 2024-04-28 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusermodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='username',
        ),
    ]
