# Generated by Django 5.0.2 on 2024-04-28 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customusermodel_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customusermodel',
            old_name='telephone',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
