# Generated by Django 5.0.2 on 2024-05-03 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_rename_telephone_customusermodel_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customusermodel",
            name="bio",
            field=models.TextField(blank=True),
        ),
    ]
